
// A curated list of 99 unique names for the House Wallets to give them a more realistic feel.
// The first wallet address is reserved for the Admin, so this list provides names for the other 99.
export const HOUSE_WALLET_NAMES = [
    "Aether Weaver",
    "Quantum Bloom",
    "Chrono Artisan",
    "Cyberspecter",
    "Helios Prime",
    "Lunara",
    "Nova Drift",
    "Oracle Engine",
    "Solstice Flare",
    "Void Walker",
    "Zenith Architect",
    "Apex Seeker",
    "Blaze Runner",
    "Cerulean",
    "Dream Catcher",
    "Echo Sphere",
    "Flux Rider",
    "Ghost Pixel",
    "Helix Nomad",
    "Ignis",
    "Jolt Master",
    "Kairo",
    "Light Speed",
    "Mirage",
    "Nebula",
    "Obsidian",
    "Pulse",
    "Quasar",
    "Rift",
    "Stryker",
    "Tesseract",
    "Umbra",
    "Vortex",
    "Wisp",
    "Xylo",
    "Yara",
    "Zephyr",
    "Arc Light",
    "Bit Shift",
    "Core",
    "Dynamo",
    "Eon",
    "Fable",
    "Grit",
    "Haze",
    "Icon",
    "Jinx",
    "Kismet",
    "Loom",
    "Moxie",
    "Nyx",
    "Omen",
    "Pylon",
    "Quest",
    "Rune",
    "Spire",
    "Tide",
    "Ursa",
    "Vesper",
    "Warden",
    "Xenon",
    "Yugen",
    "Zion",
    "Axiom",
    "Blink",
    "Catalyst",
    "Dawn",
    "Elixir",
    "Forge",
    "Glyph",
    "Haven",
    "Iris",
    "Jubilee",
    "Karma",
    "Legacy",
    "Mantra",
    "Nexus",
    "Origin",
    "Paragon",
    "Query",
    "Radiant",
    "Saga",
    "Talisman",
    "Unity",
    "Vanguard",
    "Willow",
    "Xypher",
    "Yield",
    "Zentih",
    "Alloy",
    "Bastion",
    "Crest",
    "Drift",
    "Ember",
    "Fjord",
    "Gale",
    "Harbor"
];
